fix: prevent default onkeypress action
aragon/ui pull request #817
Opened 2021-02-17 04:07 UTC by eliobricenov

### Description

Given that the `<Checkbox/>` component renders a `<span>` element with a `<button>` element as a parent, by default, the `Enter` key triggers the `keypress` event. 

This PR disables the default action on the `keypress` event that triggers the `click` event later on.

**Note**: the checkbox can still be checked with the `Space` key thanks to the `role` attribute.

Resolves #626

2021-02-17 04:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aragon/ui?pullRequest=817) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aragon/ui?pullRequest=817) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aragon/ui?pullRequest=817) it.</sub>

2021-02-23 13:16 UTC, Horus78 commented
Ufs...

2021-03-09 10:43 UTC, nivida requested changes
The change itself looks good. But was it required to update the dependencies as for example ``rollup/plugin-node-resolve``? I especially ask this because it is a major version increase. 

Overall we can say that changes per PR should be kept at a minimum. This means the description of a PR and the related issue/task defines the scope of it and any further changes have to be done in a separate PR with a related task.

2021-03-12 07:49 UTC, nivida commented
@eliobricenov Thanks for the insights! :) Feel free to create a task on Linear related to the required dependency updates and add it to the circle. I think it will be a quick thing for you to open a PR for and we would better see the work you already have done :-)

2021-03-12 07:50 UTC, nivida approved these changes

2021-03-12 07:51 UTC, merged